
_comment = "This script handles the calibration run for 3gcp."
ligand-resname = "sb2"
[reference_free_energies]


[input]
_comment = "Simulation requires an mmCIF file and a ffxml residue. Please specify the input directory under dir."
dir = "/home/mwieder/Work/Projects/protons-dev/protons/examples/tautomers/3gcp/input/"
structure = "sb2-water.cif"

[output]
dir = "/home/mwieder/Work/Projects/protons-dev/protons/examples/tautomers/sb2/output/"

[forcefield]
_comment1 = "Standard, included xml files. Don't forget -obc2 files if using implicit."
default = ["amber10-constph.xml", "gaff.xml", "tip3p.xml", "ions_tip3p.xml"]
only-tautomers = ["amber10.xml", "gaff.xml", "tip3p.xml", "ions_tip3p.xml"]
_comment2 = "Custom generated xml file (needs to be in input dir."
user-xml = ["sb2.ffxml"]


[system]
_comment1 = "Systemwide settings, such as temperature, and long range method"
_comment2 = "If PME left out, nocutoff is used."
temperature_k = 300.0
salt_concentration_molar = 0.150

[system.PME] 
_comment = "Ewald + periodic system settings"
ewald_error_tolerance = 1.0e-5
switching_distance_nm = 0.85
nonbonded_cutoff_nm = 1.0
barostat_interval = 25
pressure_atm = 1.0

[integrator]
timestep_fs = 2.0
constraint_tolerance = 1.0e-7
collision_rate_per_ps = 1.0

[preprocessing]
minimization_tolerance_kjmol = 1.0e-5
minimization_max_iterations = 300
num_thermalization_steps = 1000

[SAMS]
beta = 0.6
flatness_criterion = 0.1
sites = "one"
update_rule = "binary"
min_burn = 200
min_slow = 200
min_fast = 200

[simulation]
dcd_filename = "sb2.dcd" 
netCDF4 = "sb2.nc"
total_update_attempts = 5000
md_steps_between_updates = 100
perturbations_per_ncmc_trial = 3
propagations_per_ncmc_step = 1
timeout_sec = 21599
perturbations_per_trial = 1000

[reporters]
metadata = 1
[reporters.titration]
frequency = 1
[reporters.coordinates]
frequency = 100
[reporters.sams]
frequency = 1
[reporters.ncmc]
frequency = 1


[platform]
driver='CPU'
