package:
  name: protons-dev
  version: !!str 0.0.1a7

source:
  path: ../../

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python ==3.6
    - openmm <7.3
    - numpy >=1.10
    - scipy >=0.17.0
    - mdtraj # For extracting trajectory parts
    - netcdf4 >=1.2.4
    - hdf4 >4.2.11 # Pinned because of issue with netcdf4
    - openmmtools >=0.9.3,<=0.16.0
    - ambermini >=15.0.4
    - parmed <=2.7.3
    - joblib
    - lxml
    - pymbar
    - seaborn
    - matplotlib
    - pandas
    - saltswap >=0.5.2 # for counterion coupling
    - beautifulsoup4 # for deserialization of html tables
    - networkx # matching protonation state structures
    - tqdm # progress bar in scripts
    - pyyaml # parsing json/yaml in scripts

  run:
    - python ==3.6
    - openmm <7.3
    - numpy >=1.10
    - scipy >=0.17.0
    - mdtraj # For extracting trajectory parts
    - netcdf4 >=1.2.4
    - hdf4 >4.2.11 # Pinned because of issue with netcdf4
    - openmmtools >=0.9.3,<=0.16.0
    - ambermini >=15.0.4
    - parmed <=2.7.3
    - joblib
    - lxml
    - pymbar
    - seaborn
    - matplotlib
    - pandas
    - saltswap >=0.5.2 # for counterion coupling
    - beautifulsoup4 # for deserialization of html tables
    - networkx # matching protonation state structures
    - tqdm # progress bar in scripts
    - pyyaml # parsing json/yaml in scripts

test:
  requires:
    - pytest
    - pytest-runner
    - pytest-cov
    - behave

  imports:
    - protons

about:
  home: https://github.com/choderalab/protons
