package:
  name: protons-dev
  version: !!str 0.0.1

source:
  path: ../../

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - openmm >=7.2
    - numpy >=1.10
    - scipy >=0.17.0
    - mdtraj # For extracting trajectory parts
    - openmoltools ==0.7.5
    - openmmtools >=0.9.3
    - ambermini >=15.0.4
    - netcdf4 >=1.2.4
    - hdf4 >4.2.11 # Pinned because of issue with netcdf4
    - joblib
    - lxml
    - parmed <=2.7.3 # Newer versions break parameter generation
    - pytest
    - pytest-runner
    - pymbar
    - seaborn
    - matplotlib
    - pandas
    - beautifulsoup4 # for deserialization of html tables
    - saltswap >=0.5.2 # for counterion coupling
    - networkx # matching protonation state structures

  run:
    - python
    - openmm >=7.2
    - numpy >=1.10
    - scipy >=0.17.0
    - mdtraj # For extracting trajectory parts
    - netcdf4 >=1.2.4
    - hdf4 >4.2.11 # Pinned because of issue with netcdf4
    - openmoltools >=0.7.5
    - openmmtools >=0.9.3
    - ambermini >=15.0.4
    - parmed <=2.7.3
    - joblib
    - lxml
    - parmed
    - pymbar
    - seaborn
    - matplotlib
    - pandas
    - saltswap >=0.5.2 # for counterion coupling
    - beautifulsoup4 # for deserialization of html tables
    - networkx # matching protonation state structures
    - tqdm # progress bar in scripts

test:
  requires:
    - pytest
    - pytest-runner
    - pytest-cov
    - behave

  imports:
    - protons

about:
  home: https://github.com/choderalab/protons
