package:
  name: protons-dev
  version: !!str 0.0.0

source:
  path: ../../

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - openmm >=7.1
    - numpy >=1.10
    - scipy >=0.17.0
    - openmoltools >=0.7.5
    - openmmtools >=0.9.3
    - ambermini >=15.0.4
    - netcdf4 >=1.2.4
    - hdf4 >4.2.11 # Pinned because of issue with netcdf4
    - joblib
    - lxml
    - parmed

  run:
    - python
    - openmm >=7.1
    - numpy >=1.10
    - scipy >=0.17.0
    - netcdf4 >=1.2.4
    - hdf4 >4.2.11 # Pinned because of issue with netcdf4
    - openmoltools >=0.7.5
    - openmmtools >=0.9.3
    - ambermini >=15.0.4
    - joblib
    - lxml
    - parmed

test:
  requires:
    - pytest
    - pytest-cov
    - behave

  imports:
    - protons

about:
  home: https://github.com/choderalab/constph-openmm
