package:
  name: protons-dev
  version: !!str 0.0.0

source:
  path: ../../

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - openmm >=7.0.1
    - numpy >=1.10
    - scipy >=0.17.0
    - openmmtools >=0.7.5
    - pymbar
    - openmoltools >=0.7.0
    - ambermini
    - joblib
    - lxml

  run:
    - python
    - openmm >=7.0.1
    - numpy >=1.10
    - scipy >=0.17.0
    - openmmtools >=0.7.5
    - pymbar
    - openmoltools >=0.7.0
    - ambermini
    - joblib
    - lxml

test:
  requires:
    - pytest
    - pytest-cov
    - python-coveralls

  imports:
    - protons

about:
  home: https://github.com/choderalab/constph-openmm
