package:
  name: openmm-constph
  version: !!str 0.0.0

source:
  path: ../../

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - openmm ==7.0rc1
    - numpy >=1.10
    - scipy >=0.17.0
    - openmmtools ==0.7.5
    - pymbar
    - parmed ==2.5.1
    - openmoltools ==0.7.0
    - ambermini
    - joblib
    - lxml

  run:
    - python
    - openmm ==7.0rc1
    - numpy >=1.10
    - scipy >=0.17.0
    - openmmtools ==0.7.5
    - pymbar
    - parmed ==2.5.1
    - openmoltools ==0.7.0
    - ambermini
    - joblib
    - lxml

test:
  requires:
    - nose
    - coverage
    - numpy
    - python-coveralls

  imports:
    - constph

about:
  home: https://github.com/choderalab/openmm-constph
